// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaia69lPXHVtCCjKn24JsENMOLD5ziogI',
    appId: '1:964677636877:web:893049ac98126c16785644',
    messagingSenderId: '964677636877',
    projectId: 'micki-nas',
    authDomain: 'micki-nas.firebaseapp.com',
    storageBucket: 'micki-nas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsR8-KaGz_rlooGtfryNWXBv5DjCgmV4',
    appId: '1:964677636877:android:3cd8526d46358e69785644',
    messagingSenderId: '964677636877',
    projectId: 'micki-nas',
    storageBucket: 'micki-nas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANTdD-FsODKRzCyTTRGINvYzP-8ZQaeDk',
    appId: '1:964677636877:ios:d13cdc2d0c4737a1785644',
    messagingSenderId: '964677636877',
    projectId: 'micki-nas',
    storageBucket: 'micki-nas.firebasestorage.app',
    iosBundleId: 'com.example.bachelorsFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANTdD-FsODKRzCyTTRGINvYzP-8ZQaeDk',
    appId: '1:964677636877:ios:d13cdc2d0c4737a1785644',
    messagingSenderId: '964677636877',
    projectId: 'micki-nas',
    storageBucket: 'micki-nas.firebasestorage.app',
    iosBundleId: 'com.example.bachelorsFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaia69lPXHVtCCjKn24JsENMOLD5ziogI',
    appId: '1:964677636877:web:92e18692efb756ab785644',
    messagingSenderId: '964677636877',
    projectId: 'micki-nas',
    authDomain: 'micki-nas.firebaseapp.com',
    storageBucket: 'micki-nas.firebasestorage.app',
  );
}
